function [controls] = createControls(parentTab, nodePos, nodeHandles)
    controlPanel = uipanel(parentTab,'Title','Network Controls & Status',...
                          'Position',[0.52 0.35 0.46 0.6],'FontSize',12,'FontWeight','bold','BackgroundColor','white');
    % Source Node
    uicontrol(controlPanel,'Style','text','Position',[30 320 120 25],...
              'String','Source Node:','FontSize',11,'FontWeight','bold',...
              'HorizontalAlignment','left','BackgroundColor','white');
    controls.sourceNodeDropdown = uicontrol(controlPanel,'Style','popupmenu',...
                          'Position',[30 290 120 30],...
                          'String',arrayfun(@(x) ['Node ',num2str(x)],1:size(nodePos,1),'UniformOutput',false),...
                          'FontSize',10,'BackgroundColor','white');
    % Destination Node
    uicontrol(controlPanel,'Style','text','Position',[180 320 140 25],...
              'String','Destination Node:','FontSize',11,'FontWeight','bold',...
              'HorizontalAlignment','left','BackgroundColor','white');
    controls.destNodeDropdown = uicontrol(controlPanel,'Style','popupmenu',...
                          'Position',[180 290 120 30],...
                          'String',arrayfun(@(x) ['Node ',num2str(x)],1:size(nodePos,1),'UniformOutput',false),...
                          'FontSize',10,'BackgroundColor','white');
    % Transfer Button
    controls.transferBtn = uicontrol(controlPanel,'Style','pushbutton',...
                           'Position',[330 290 120 35],...
                           'String','Transfer Data','FontSize',12,'FontWeight','bold',...
                           'BackgroundColor',[0.2 0.6 1],'ForegroundColor','white');
    % Fault list
    faultText = uicontrol(controlPanel,'Style','text','Position',[30 220 120 25],...
                     'String','Transfer Log:','FontSize',11,'FontWeight','bold',...
                     'HorizontalAlignment','left','BackgroundColor','white');
    controls.faultList = uicontrol(controlPanel,'Style','listbox','Position',[30 50 420 160],...
                     'FontSize',10,'BackgroundColor','white');
end
